version: "3.8"

services:
  node:
    image: node:20
    container_name: vue-tournament
    working_dir: /app
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "3000:5173"
      - "6006:6006"
      - "6007:6007"
    command: ./docker/node/start.sh
    environment:
      - NODE_ENV=development