version: "3.8"

services:
  node:
    image: node:20
    container_name: my-npm-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:5173"
      - "6006:6006"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development