version: "3.8"

services:
  node:
    image: node:20
    container_name: vue-tournament
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:5173"
      - "6006:6006"
    command: ./start.sh
    environment:
      - NODE_ENV=development