name: Lint, Build Docs, and Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check ESLint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run lint

  storybook:
    needs: lint
    name: Build storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm i
      - name: Build with VitePress
        run: npm run build-storybook
      - run: |
          mkdir -p deploy/storybook
          cp -r storybook-static/* deploy/storybook/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  doc:
    needs: lint
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm i
      - name: Build with VitePress
        run: npm run docs:build
      - run: |
          mkdir -p deploy/documentation
          cp -r docs/.vitepress/dist/* deploy/documentation/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deployStorybook:
    environment:
      name: github-pages
    needs: storybook
    runs-on: ubuntu-latest
    name: Publish storybook to github pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deployDoc:
    environment:
      name: github-pages
    needs: doc
    runs-on: ubuntu-latest
    name: Publish documentation to github pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4